#!/bin/sh
set -e

Cmdline ()
{
    # Reading kernel command line
    for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
    do
        case "${_PARAMETER}" in
            live-config.username=*|username=*)
                LIVE_USERNAME="${_PARAMETER#*username=}"
                ;;
        esac
    done
}

Init ()
{
    :
}

Config ()
{
    mkdir -p /home/${LIVE_USERNAME}/.config/autostart
    ln -s /usr/share/applications/openwebrx.desktop /home/${LIVE_USERNAME}/.config/autostart/
    chown -R ${LIVE_USERNAME}. /home/${LIVE_USERNAME}/.config

    mkdir -p /home/${LIVE_USERNAME}/Desktop
    cat > /home/${LIVE_USERNAME}/Desktop/openwebrx.desktop << EOF
[Desktop Entry]
Type=Link
Name=OpenWebRX
URL=/usr/share/applications/openwebrx.desktop
EOF
    chmod +x /home/${LIVE_USERNAME}/Desktop/openwebrx.desktop
    chown -R ${LIVE_USERNAME}. /home/${LIVE_USERNAME}/Desktop
}

Cmdline
Init
Config
