#!/bin/sh
set -e

Cmdline ()
{
    # Reading kernel command line
    for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
    do
        case "${_PARAMETER}" in
            live-config.username=*|username=*)
                LIVE_USERNAME="${_PARAMETER#*username=}"
                ;;
        esac
    done
}

Init ()
{
    :
}

Config ()
{
    # set the system up to autostart a browser with openwebrx immediately
    mkdir -p /home/${LIVE_USERNAME}/.config/autostart
    ln -s /usr/share/applications/openwebrx.desktop /home/${LIVE_USERNAME}/.config/autostart/
    chown -R ${LIVE_USERNAME}. /home/${LIVE_USERNAME}/.config

    mkdir -p /home/${LIVE_USERNAME}/Desktop

    # put openwebrx on the desktop
    cat > /home/${LIVE_USERNAME}/Desktop/openwebrx.desktop << EOF
[Desktop Entry]
Type=Link
Name=OpenWebRX
Icon=openwebrx
URL=/usr/share/applications/openwebrx.desktop
EOF

    # add an installer link to the desktop
    cat > /home/${LIVE_USERNAME}/Desktop/debian-installer-launcher.desktop << EOF
[Desktop Entry]
Type=Link
Name=Install Debian
Icon=debian-installer-launcher
URL=/usr/share/applications/debian-installer-launcher.desktop
EOF

    chown -R ${LIVE_USERNAME}. /home/${LIVE_USERNAME}/Desktop
}

Cmdline
Init
Config
