#!/bin/sh
set -e

Cmdline ()
{
    # Reading kernel command line
    for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
    do
        case "${_PARAMETER}" in
            live-config.username=*|username=*)
                LIVE_USERNAME="${_PARAMETER#*username=}"
                ;;
        esac
    done
}

Init ()
{
    :
}

Config ()
{
    PROFILE_DIR=/home/${LIVE_USERNAME}/.mozilla/firefox/openwebrx.profile/
    mkdir -p ${PROFILE_DIR}
    cat > ${PROFILE_DIR}/xulstore.json << EOF
{"chrome://browser/content/browser.xul":{"main-window":{"screenX":"0","screenY":"0","width":"1280","height":"1040","sizemode":"maximized"}}}
EOF

    cat > ${PROFILE_DIR}/prefs.js << EOF
user_pref("browser.startup.homepage", "http://localhost:8073/");
EOF

    chown -R ${LIVE_USERNAME}. /home/${LIVE_USERNAME}/.mozilla
}

Cmdline
Init
Config
